# Generated by Django 4.0.6 on 2022-07-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='traces',
        ),
    ]
