# Generated by Django 4.0.6 on 2022-07-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={},
        ),
    ]
