# Generated by Django 4.0.6 on 2022-07-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_alter_points_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={},
        ),
    ]
