# Generated by Django 4.0.6 on 2022-07-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traces',
            name='trace',
        ),
    ]
