# Generated by Django 4.0.6 on 2022-07-10 17:24

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_alter_points_options'),
        ('tracer', '0004_alter_traces_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traces',
            name='points',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, related_name='included_points', sorted=False, to='points.points'),
        ),
    ]
