# Generated by Django 4.0.6 on 2022-07-10 18:50

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_alter_points_options'),
        ('tracer', '0006_alter_traces_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='traces',
            name='break_points',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='traces',
            name='points',
            field=sortedm2m.fields.SortedManyToManyField(related_name='included_points', sorted=False, to='points.points'),
        ),
    ]
